[package]
name = "grrs"
version = "0.1.0"
authors = ["Glenn Field <glenn@riskroller.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
magic-crypt = "3.1.8"